theme: jekyll-theme-minimal
title: GoblinInTheBack's Portfolio
description: A showcase of projects, skills, and creative work
author: GoblinInTheBack
github:
  url: https://github.com/GoblinInTheBack
show_downloads: false
plugins:
  - jekyll-feed
  - jekyll-seo-tag
